"""initial_schema

Revision ID: bb06e74d2cff
Revises: 
Create Date: 2026-07-14 08:30:11.524156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers
revision: str = 'bb06e74d2cff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('activity_log', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('activity_log', 'target_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('activity_log', 'detail',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('activity_log', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_activity_target'), table_name='activity_log')
    op.drop_index(op.f('idx_activity_user'), table_name='activity_log')
    op.alter_column('bug_record', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('bug_record', 'bug_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('bug_record', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('bug_record', 'reproduce_rate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'test_env',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'root_cause',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'solution',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'tester',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('bug_record', 'comment',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bug_record', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_bug_project'), table_name='bug_record')
    op.drop_index(op.f('idx_bug_status'), table_name='bug_record')
    op.alter_column('device_config', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('device_config', 'config_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('device_config', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('device_config', 'bios_vendor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bios_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bios_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'ec_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'ec_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'motherboard',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'mb_material_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpu_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpu_frequency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpu_cores',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('device_config', 'memory_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('device_config', 'disk_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('device_config', 'gpu_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'gpu_driver',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'panel_info',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'panel_resolution',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'wlan_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'wlan_driver',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'lan_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'lan_driver',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bt_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bt_driver',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'audio_codec',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'audio_driver',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'camera_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'fingerprint_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'touchpad_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'touchpad_driver',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cardreader_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'adapter_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'battery_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'chassis',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'psu_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'odd_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_build',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_kernel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpld_hw_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpld_sw_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'mcu_hw_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'mcu_sw_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'software_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('device_config', 'raw_data',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('device_config', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('heat_test_data', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('heat_test_data', 'item_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('heat_test_data', 'item_note',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('heat_test_data', 'spec_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('heat_test_data', 'test_result',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('heat_test_data', 'comment',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('notification', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('notification', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('notification', 'content',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('notification', 'noti_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'system'"))
    op.alter_column('notification', 'target_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('notification', 'is_read',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notification', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_noti_read'), table_name='notification')
    op.drop_index(op.f('idx_noti_user'), table_name='notification')
    op.add_column('performance_data', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('performance_data', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('performance_data', 'test_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('performance_data', 'sku_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('performance_data', 'metric_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('performance_data', 'metric_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('performance_data', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('performance_data', 'raw_output',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_index(op.f('idx_perf_project'), table_name='performance_data')
    op.alter_column('product', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('product', 'product_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('product', 'line_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('product', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'planning'"))
    op.alter_column('product', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('product', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('product', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_product_line'), table_name='product')
    op.drop_index(op.f('idx_product_owner'), table_name='product')
    op.drop_index(op.f('idx_product_status'), table_name='product')
    op.alter_column('product_image', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('product_image', 'image_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('product_image', 'image_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('product_image', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('product_image', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('report_artifact', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('report_artifact', 'artifact_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('report_artifact', 'file_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('report_artifact', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('report_artifact', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('report_artifact', 'meta_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('report_artifact', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_report_artifact_batch'), table_name='report_artifact')
    op.drop_index(op.f('idx_report_artifact_project'), table_name='report_artifact')
    op.create_foreign_key(None, 'report_artifact', 'report_batch', ['batch_id'], ['id'])
    op.create_foreign_key(None, 'report_artifact', 'report_project', ['project_id'], ['id'])
    op.alter_column('report_batch', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('report_batch', 'batch_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('report_batch', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('report_batch', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'"))
    op.alter_column('report_batch', 'summary_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('report_batch', 'note',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_batch', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_report_batch_project'), table_name='report_batch')
    op.drop_index(op.f('idx_report_batch_type'), table_name='report_batch')
    op.create_foreign_key(None, 'report_batch', 'report_project', ['project_id'], ['id'])
    op.alter_column('report_project', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('report_project', 'project_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('report_project', 'product_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('report_project', 'product_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('report_project', 'tester',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('report_project', 'reviewer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'approver',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'test_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'new'"))
    op.alter_column('report_project', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('report_project', 'conclusion',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'remark',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'project_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'project'"))
    op.alter_column('report_project', 'view_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'list'"))
    op.alter_column('report_project', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_project', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_project_parent'), table_name='report_project')
    op.drop_index(op.f('idx_project_product'), table_name='report_project')
    op.drop_index(op.f('idx_project_status'), table_name='report_project')
    op.drop_index(op.f('idx_project_template'), table_name='report_project')
    op.alter_column('report_template', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('report_template', 'template_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('report_template', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('report_template', 'doc_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('report_template', 'version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'"))
    op.alter_column('report_template', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('report_template', 'product_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('report_template', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_template', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('requirement', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('requirement', 'req_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('requirement', 'req_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'business'"))
    op.alter_column('requirement', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'acceptance',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('requirement', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('requirement', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'module',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'effort_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('requirement', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('requirement', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_req_assigned'), table_name='requirement')
    op.drop_index(op.f('idx_req_project'), table_name='requirement')
    op.drop_index(op.f('idx_req_status'), table_name='requirement')
    op.drop_index(op.f('idx_req_type'), table_name='requirement')
    op.alter_column('requirement_change', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('requirement_change', 'field_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('requirement_change', 'old_value',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement_change', 'new_value',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement_change', 'change_reason',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement_change', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_foreign_key(None, 'requirement_change', 'requirement', ['req_id'], ['id'])
    op.alter_column('task', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('task', 'task_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('task', 'task_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'task'"))
    op.alter_column('task', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('task', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'"))
    op.alter_column('task', 'effort_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('task', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('task', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('task', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_task_assigned'), table_name='task')
    op.drop_index(op.f('idx_task_project'), table_name='task')
    op.drop_index(op.f('idx_task_req'), table_name='task')
    op.drop_index(op.f('idx_task_status'), table_name='task')
    op.create_foreign_key(None, 'task', 'requirement', ['req_id'], ['id'])
    op.alter_column('test_category', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('test_category', 'category_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('test_category', 'category_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('test_category', 'sheet_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('test_category', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_item', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('test_item', 'item_no',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('test_item', 'test_case',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_item', 'condition_desc',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_item', 'criteria',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_item', 'is_header',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_item', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_record', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('test_record', 'result',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'comment',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'evidence',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'tester',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('test_record', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_record_project'), table_name='test_record')
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'salt',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('user', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('user', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    op.alter_column('user', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    op.alter_column('user', 'display_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('user', 'salt',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_record_project'), 'test_record', ['project_id'], unique=False)
    op.alter_column('test_record', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('test_record', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('test_record', 'tester',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'evidence',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'comment',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'result',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_record', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('test_item', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('test_item', 'is_header',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('test_item', 'criteria',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_item', 'condition_desc',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_item', 'test_case',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('test_item', 'item_no',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('test_item', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('test_category', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('test_category', 'sheet_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('test_category', 'category_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('test_category', 'category_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('test_category', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_index(op.f('idx_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('idx_task_req'), 'task', ['req_id'], unique=False)
    op.create_index(op.f('idx_task_project'), 'task', ['project_id'], unique=False)
    op.create_index(op.f('idx_task_assigned'), 'task', ['assigned_to'], unique=False)
    op.alter_column('task', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('task', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('task', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('task', 'effort_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('task', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'"))
    op.alter_column('task', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('task', 'task_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'task'"))
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('task', 'task_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('task', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'requirement_change', type_='foreignkey')
    op.alter_column('requirement_change', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('requirement_change', 'change_reason',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement_change', 'new_value',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement_change', 'old_value',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement_change', 'field_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('requirement_change', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_req_type'), 'requirement', ['req_type'], unique=False)
    op.create_index(op.f('idx_req_status'), 'requirement', ['status'], unique=False)
    op.create_index(op.f('idx_req_project'), 'requirement', ['project_id'], unique=False)
    op.create_index(op.f('idx_req_assigned'), 'requirement', ['assigned_to'], unique=False)
    op.alter_column('requirement', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('requirement', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('requirement', 'effort_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('requirement', 'module',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'source',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('requirement', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('requirement', 'acceptance',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('requirement', 'req_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'business'"))
    op.alter_column('requirement', 'req_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('requirement', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('report_template', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_template', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_template', 'product_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_template', 'category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_template', 'version',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'"))
    op.alter_column('report_template', 'doc_code',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_template', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_template', 'template_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_template', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_project_template'), 'report_project', ['template_id'], unique=False)
    op.create_index(op.f('idx_project_status'), 'report_project', ['status'], unique=False)
    op.create_index(op.f('idx_project_product'), 'report_project', ['product_id'], unique=False)
    op.create_index(op.f('idx_project_parent'), 'report_project', ['parent_id'], unique=False)
    op.alter_column('report_project', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_project', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_project', 'view_mode',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'list'"))
    op.alter_column('report_project', 'project_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'project'"))
    op.alter_column('report_project', 'remark',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'conclusion',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('report_project', 'test_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'new'"))
    op.alter_column('report_project', 'approver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'reviewer',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_project', 'tester',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_project', 'product_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_project', 'product_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_project', 'project_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_project', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'report_batch', type_='foreignkey')
    op.create_index(op.f('idx_report_batch_type'), 'report_batch', ['project_id', 'batch_type'], unique=False)
    op.create_index(op.f('idx_report_batch_project'), 'report_batch', ['project_id'], unique=False)
    op.alter_column('report_batch', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_batch', 'note',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('report_batch', 'summary_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('report_batch', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'"))
    op.alter_column('report_batch', 'source',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('report_batch', 'batch_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_batch', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'report_artifact', type_='foreignkey')
    op.drop_constraint(None, 'report_artifact', type_='foreignkey')
    op.create_index(op.f('idx_report_artifact_project'), 'report_artifact', ['project_id'], unique=False)
    op.create_index(op.f('idx_report_artifact_batch'), 'report_artifact', ['batch_id'], unique=False)
    op.alter_column('report_artifact', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('report_artifact', 'meta_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('report_artifact', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('report_artifact', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_artifact', 'file_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_artifact', 'artifact_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_artifact', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('product_image', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('product_image', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('product_image', 'image_label',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('product_image', 'image_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('product_image', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_product_status'), 'product', ['status'], unique=False)
    op.create_index(op.f('idx_product_owner'), 'product', ['owner_id'], unique=False)
    op.create_index(op.f('idx_product_line'), 'product', ['line_name'], unique=False)
    op.alter_column('product', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('product', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('product', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('product', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'planning'"))
    op.alter_column('product', 'line_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('product', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('product', 'product_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('product', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_perf_project'), 'performance_data', ['project_id'], unique=False)
    op.alter_column('performance_data', 'raw_output',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('performance_data', 'unit',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('performance_data', 'metric_value',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('performance_data', 'metric_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('performance_data', 'sku_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('performance_data', 'test_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('performance_data', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('performance_data', 'created_at')
    op.create_index(op.f('idx_noti_user'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('idx_noti_read'), 'notification', ['user_id', 'is_read'], unique=False)
    op.alter_column('notification', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('notification', 'is_read',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notification', 'target_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('notification', 'noti_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'system'"))
    op.alter_column('notification', 'content',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('notification', 'title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notification', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('heat_test_data', 'comment',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('heat_test_data', 'test_result',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('heat_test_data', 'spec_value',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('heat_test_data', 'item_note',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('heat_test_data', 'item_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('heat_test_data', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('device_config', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('device_config', 'raw_data',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('device_config', 'software_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('device_config', 'mcu_sw_version',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'mcu_hw_version',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpld_sw_version',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpld_hw_version',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_kernel',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_language',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_build',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'os_version',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'odd_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'psu_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'chassis',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'battery_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'adapter_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cardreader_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'touchpad_driver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'touchpad_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'fingerprint_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'camera_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'audio_driver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'audio_codec',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bt_driver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bt_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'lan_driver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'lan_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'wlan_driver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'wlan_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'panel_resolution',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'panel_info',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'gpu_driver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'gpu_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'disk_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('device_config', 'memory_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('device_config', 'cpu_cores',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('device_config', 'cpu_frequency',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'cpu_model',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'mb_material_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'motherboard',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'ec_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'ec_version',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bios_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bios_version',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'bios_vendor',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('device_config', 'source',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('device_config', 'config_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('device_config', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_bug_status'), 'bug_record', ['status'], unique=False)
    op.create_index(op.f('idx_bug_project'), 'bug_record', ['project_id'], unique=False)
    op.alter_column('bug_record', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bug_record', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bug_record', 'comment',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'open'"))
    op.alter_column('bug_record', 'tester',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'solution',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'root_cause',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'test_env',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'reproduce_rate',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'severity',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('bug_record', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('bug_record', 'bug_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bug_record', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_activity_user'), 'activity_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_activity_target'), 'activity_log', ['target_type', 'target_id'], unique=False)
    op.alter_column('activity_log', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('activity_log', 'detail',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('activity_log', 'target_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('activity_log', 'action',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('activity_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
